# Generated by Django 5.2.5 on 2025-08-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_choice', models.CharField(choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=10)),
                ('computer_choice', models.CharField(choices=[('rock', 'Rock'), ('paper', 'Paper'), ('scissors', 'Scissors')], max_length=10)),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rps_game.player')),
            ],
        ),
    ]
